In [1]:
import numpy as np
np.__version__

'1.22.2'

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
np.ones([2, 2], dtype=int)

array([[1, 1],
       [1, 1]])

In [10]:
np.ones([3, 2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
X = np.arange(4, dtype=int)
np.ones_like(X)

array([1, 1, 1, 1])

In [15]:
X = np.array(([1,2,3], [4,5,6]), dtype=int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones([4, 4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.randint(10, size=3)

array([9, 8, 7])

In [19]:
np.random.randn(3, 3, 3)

array([[[-1.58674931,  0.64145347, -0.14772377],
        [-0.42452052,  0.4010346 ,  0.57630477],
        [ 0.78335646, -0.0497653 , -0.59259692]],

       [[-1.24472073, -1.1964914 , -0.39707245],
        [ 0.1994079 , -0.81930904,  1.25125502],
        [ 0.52323566,  0.03227671,  0.31404662]],

       [[ 0.91824845, -0.65998726, -1.41546731],
        [-0.37885701, -0.10664695, -0.43293448],
        [-0.55277321, -0.4688077 ,  0.66462566]]])

In [21]:
X = [1, 2, 3]
Y = np.array(X)
Y

array([1, 2, 3])

In [23]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
X = np.arange(25).reshape(5, 5)
X[0], X[-1], X[0, 0], X[1:-1, 1:-1], X[2:, 2:]

(array([0, 1, 2, 3, 4]),
 array([20, 21, 22, 23, 24]),
 0,
 array([[ 6,  7,  8],
        [11, 12, 13],
        [16, 17, 18]]),
 array([[12, 13, 14],
        [17, 18, 19],
        [22, 23, 24]]))

In [33]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [34]:
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [35]:
mask = X > 5
X[mask]

array([ 6, 10])

In [37]:
mask = X > X.mean()
X.mean(), X[mask]

(0.9, array([ 2,  5,  6, 10]))

In [38]:
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

In [40]:
X.all() # verifica se todos elementos == 0

False

In [41]:
X.any()

True

In [46]:
X = np.arange(1, 26).reshape(5, 5)
X.sum(axis=0)  # axis=0 colunas; axis=1 linhas

array([55, 60, 65, 70, 75])

In [48]:
X.mean(axis=1)

array([ 3.,  8., 13., 18., 23.])

In [49]:
X.max()

25