### NumPy: Numeric Computing Library
Não é tão usado diretamente em aplicações, mas sim, muitas das outras bibliotecas a utilizam<br>
-> Python perde eficiência computacional ao realizar cálculos grandes de forma eficiente, NumPy tenta corrigir isso<br>
-> API em C que conecta NumPy com bibliotecas em C, C++ ou Fortran

In [1]:
import sys
import numpy as np

In [2]:
np.int8   # numero de apenas 8 bits (python seriam 20 bytes)

# lista não é otimizada para processamento de dados em python (pode estar em posições não contínuas de memória)
np.array([1, 2, 3])     # garantidamente estarão em posições continuas de memória
# pode usar instruções para processamento de vetor e matriz da CPU

array([1, 2, 3])

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5, 2])

In [4]:
a[0], a[1]

(1, 2)

In [5]:
print(a[0:])

[1 2 3 4]


In [6]:
a[0:2]


array([1, 2])

In [7]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [8]:
b[[0, 2, -1]]

array([0., 1., 2.])

#### Array Types

In [9]:
a

array([1, 2, 3, 4])

In [10]:
a.dtype

dtype('int32')

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b.dtype

dtype('float64')

In [13]:
np.array([1, 2, 3, 4], dtype=float)
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [14]:
c = np.array(["a", "b", "c"])
c.dtype

dtype('<U1')

In [15]:
d = np.array([{"a":1}, sys])
d.dtype

dtype('O')

#### Dimensions and shapes; indexing  and slicing

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]    
])

In [17]:
print(A.shape)
print(A.ndim)
print(A.size)

(2, 3)
2
6


In [18]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [19]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [20]:
print(B.shape)
print(B.ndim)
print(B.size)

(2, 2, 3)
3
12


In [21]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]    
])
print(A[1, 0])   # linha 1, coluna 0, A[dim1, dim2, dim3, ...]
print(A[0:2])

4
[[1 2 3]
 [4 5 6]]


In [22]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [23]:
A[:2, 2:]

array([[3],
       [6]])

In [24]:
A[1] = np.array([10, 10, 10])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [25]:
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#### Estatísticas e métodos

In [26]:
a = np.array([1, 2, 3, 4])

In [31]:
print(a.sum())
print(a.mean())
print(a.std())
print(a.var())

10
2.5
1.118033988749895
1.25


In [32]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]    
])

In [33]:
print(A.sum())
print(A.mean())
print(A.std())

45
5.0
2.581988897471611


In [38]:
print(A.sum(axis=0))  # soma das colunas
print(A.sum(axis=1))  # soma das linhas
# funciona para os métodos a cima e para mais dimensões caso existam

[12 15 18]
[ 6 15 24]


#### Broadcasting and vectorized operations
-> otimizadas!

In [40]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [41]:
a + 10

array([10, 11, 12, 13])

In [42]:
a * 10

array([ 0, 10, 20, 30])

In [48]:
a += 100
a

array([600, 601, 602, 603])

In [49]:
l = [0, 1, 2, 3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [50]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [51]:
b = np.array([10, 10, 10, 10])

print(a + b)
print(a * b)

[10 11 12 13]
[ 0 10 20 30]


#### Boolean arrays

In [52]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [53]:
a[[0, -1]]

array([0, 3])

In [55]:
a[[True, False, False, True]]

array([0, 3])

In [56]:
a >= 2

array([False, False,  True,  True])

In [57]:
a[a >= 2]

array([2, 3])

In [58]:
a.mean()

1.5

In [59]:
a[a > a.mean()]

array([2, 3])

In [60]:
a[~(a > a.mean())]

array([0, 1])

In [61]:
# | = or; & = and; ~ = not
a[(a == 0) | (a == 1)]

array([0, 1])

#### Linear Algebra

In [62]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [64]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [66]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [67]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [68]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [69]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#### Size of objects in memory

In [72]:
# inteiro em python >24 bytes
print(sys.getsizeof(1))
# long
print(sys.getsizeof(10**100))

28
72


In [75]:
print(np.dtype(np.int8).itemsize)
print(np.dtype(int).itemsize)
print(np.dtype(float).itemsize)

1
4
8


In [76]:
print(sys.getsizeof([1]))
print(np.array([1]).nbytes)

64
4


In [118]:
l = list(range(100000))
a = np.arange(100000, dtype=np.int32)

In [119]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 25 ms


333328333350000

In [117]:
%time np.sum(a ** 2)

CPU times: total: 15.6 ms
Wall time: 999 µs


216474736

#### Funções úteis

In [123]:
# random
print(np.random.random(size=2))
print(np.random.normal(size=2))
print(np.random.rand(2, 4))

[0.39503593 0.05036415]
[0.10815821 0.63671101]
[[0.75643522 0.13360487 0.42820406 0.22820283]
 [0.49033429 0.75148733 0.69830077 0.72635948]]


In [127]:
# arange
print(np.arange(10))
print(np.arange(5, 10))
print(np.arange(0, 1, .1))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [128]:
# reshape
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [129]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [130]:
# linspace
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [131]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [132]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [160]:
# zeros, ones, empty
print(np.zeros(5))
print(np.zeros((3, 3)))
print(np.zeros((3, 3), dtype=int))
print()
print(np.ones(5))
print(np.ones((3, 3)))
print()
print(np.empty(5))
print(np.empty((2, 2)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[1. 1. 1. 1. 1.]
[[0.25 0.5 ]
 [0.75 1.  ]]
